// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yelanwtucirrxbskwjxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllbGFud3R1Y2lycnhic2t3anhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NDcyNjAsImV4cCI6MjA3MzAyMzI2MH0.uyrfsLjgZfW4uWAZ7XO_nfMwhgChx1ehzvWgdA4Q7h8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  // Ensure network requests bypass any caches and are CORS-safe even when a SW is present
  global: {
    fetch: (input: RequestInfo | URL, init?: RequestInit) => {
      const url = typeof input === 'string' || input instanceof URL ? String(input) : (input as Request).url;
      const nextInit: RequestInit = {
        ...init,
        // Always go to network for auth and DB requests
        cache: 'no-store',
        // Avoid sending cookies to third-party origins
        credentials: 'omit',
        mode: 'cors',
        redirect: 'follow',
      };
      return fetch(input as any, nextInit);
    },
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
